# main.py — Generated by VIA for: Build a simple task manager where users can add, complete, and delete tasks — deploy it fully.
from fastapi import FastAPI, HTTPException, Depends
from fastapi.middleware.cors import CORSMiddleware
from database import engine, get_db
from models import Base, Item
from sqlalchemy.orm import Session
import os

app = FastAPI(
    title="Build A Simple Task Manager Where",
    description="Generated by VIA — Autonomous AI Digital Team",
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.on_event("startup")
def on_startup():
    try:
        Base.metadata.create_all(bind=engine)
    except Exception as e:
        import logging as _log
        _log.getLogger("via").warning(f"DB init warning: {e}")



@app.get("/")
def root():
    return {"app": "Build A Simple Task Manager Where", "status": "running", "generated_by": "VIA"}

@app.get("/health")
def health():
    return {"status": "healthy"}


@app.get("/api/v1/items")
def get_items(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    items = db.query(Item).offset(skip).limit(limit).all()
    return {"items": [{"id": i.id, "title": i.title, "description": i.description,
                       "status": i.status, "created_at": str(i.created_at)} for i in items],
            "total": db.query(Item).count()}

@app.get("/api/v1/items/{item_id}")
def get_item(item_id: int, db: Session = Depends(get_db)):
    item = db.query(Item).filter(Item.id == item_id).first()
    if not item:
        raise HTTPException(status_code=404, detail="Item not found")
    return {"id": item.id, "title": item.title, "description": item.description,
            "status": item.status, "created_at": str(item.created_at)}

@app.post("/api/v1/items")
def create_item(payload: dict, db: Session = Depends(get_db)):
    item = Item(title=payload.get("title", "Untitled"),
                description=payload.get("description", ""),
                status=payload.get("status", "active"))
    db.add(item); db.commit(); db.refresh(item)
    return {"id": item.id, "title": item.title, "description": item.description,
            "status": item.status, "created_at": str(item.created_at)}

@app.put("/api/v1/items/{item_id}")
def update_item(item_id: int, payload: dict, db: Session = Depends(get_db)):
    item = db.query(Item).filter(Item.id == item_id).first()
    if not item:
        raise HTTPException(status_code=404, detail="Item not found")
    for key, val in payload.items():
        if hasattr(item, key):
            setattr(item, key, val)
    db.commit(); db.refresh(item)
    return {"id": item.id, "title": item.title, "description": item.description, "status": item.status}

@app.delete("/api/v1/items/{item_id}")
def delete_item(item_id: int, db: Session = Depends(get_db)):
    item = db.query(Item).filter(Item.id == item_id).first()
    if not item:
        raise HTTPException(status_code=404, detail="Item not found")
    db.delete(item); db.commit()
    return {"deleted": item_id}

@app.get("/api/v1/stats")
def get_stats(db: Session = Depends(get_db)):
    total  = db.query(Item).count()
    active = db.query(Item).filter(Item.status == "active").count()
    return {"total": total, "active": active}

# ── Route aliases: /api/v1/tasks and /tasks mirror /api/v1/items ────
@app.get("/api/v1/tasks")
def alias_get_tasks(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    return get_items(skip=skip, limit=limit, db=db)

@app.post("/api/v1/tasks")
def alias_create_tasks(payload: dict, db: Session = Depends(get_db)):
    return create_item(payload=payload, db=db)

@app.get("/api/v1/tasks/{item_id}")
def alias_get_tasks_one(item_id: int, db: Session = Depends(get_db)):
    return get_item(item_id=item_id, db=db)

@app.put("/api/v1/tasks/{item_id}")
def alias_update_tasks(item_id: int, payload: dict, db: Session = Depends(get_db)):
    return update_item(item_id=item_id, payload=payload, db=db)

@app.delete("/api/v1/tasks/{item_id}")
def alias_delete_tasks(item_id: int, db: Session = Depends(get_db)):
    return delete_item(item_id=item_id, db=db)

@app.get("/tasks")
def alias_get_tasks_short(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    return get_items(skip=skip, limit=limit, db=db)

@app.post("/tasks")
def alias_create_tasks_short(payload: dict, db: Session = Depends(get_db)):
    return create_item(payload=payload, db=db)

@app.get("/tasks/{item_id}")
def alias_get_tasks_short_one(item_id: int, db: Session = Depends(get_db)):
    return get_item(item_id=item_id, db=db)

@app.put("/tasks/{item_id}")
def alias_update_tasks_short(item_id: int, payload: dict, db: Session = Depends(get_db)):
    return update_item(item_id=item_id, payload=payload, db=db)

@app.delete("/tasks/{item_id}")
def alias_delete_tasks_short(item_id: int, db: Session = Depends(get_db)):
    return delete_item(item_id=item_id, db=db)


if __name__ == "__main__":
    import uvicorn
    port = int(os.getenv("PORT", 8000))
    uvicorn.run("main:app", host="0.0.0.0", port=port, reload=False)
